apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: runas65534uid
runAsUser:
  type: MustRunAs
  uid: 65534
seLinuxContext:
  type: RunAsAny
supplementalGroups:
  type: MustRunAs
  gid: 65534