apiVersion: v1
kind: ConfigMap
metadata:
    name: prometheus-config
    namespace: victoria-metrics-test
data:
    prometheus-config.yml: |-
        global:
            external_labels:
              monitor: test
            scrape_interval:     15s
            evaluation_interval: 15s

        remote_write:
          - url: http://vmcluster-victoria-metrics-cluster-vminsert.victoria-metrics-test.svc.cluster.local:8480/insert/0/prometheus/

        scrape_configs:
          - job_name: prometheus
            static_configs:
              - targets: ['localhost:9090']