apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: grafana-test
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - grafana-scc
  resources:
  - securitycontextconstraints
  verbs:
  - use