apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: grafana-scc
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
fsGroup:
  type: RunAsAny