apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: grafana-role-binding
  namespace: grafana-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: grafana-scc
subjects:
- kind: ServiceAccount
  name: grafana-test
  namespace: grafana-test