apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    namespace: cortex-test
    name: cortex-claim
spec:
    accessModes:
      - ReadWriteOnce
    resources:
        requests:
            storage: 1G
    storageClassName: managed-premium