apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: cortex-role-binding
  namespace: cortex-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cortex-test
subjects:
- kind: ServiceAccount
  name: default
  namespace: cortex-test