apiVersion: apps/v1
kind: Deployment
metadata:
  name: cortex
  namespace: cortex-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cortex
  template:
    metadata:
      labels:
        app: cortex
    spec:
      containers:
      - image: cortexproject/cortex:v1.10.0
        args:
          - --config.file=/etc/cortex/config/cortex-config.yml
        imagePullPolicy: IfNotPresent
        name: cortex
        ports:
        - containerPort: 9009
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/cortex/config/
          name: cortex-config
        - mountPath: /tmp/cortex
          name: cortex-claim
        - mountPath: /prometheus
          name: cortex-prometheus-claim
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            default-mode: 660
            items:
              - key: cortex-config.yml
                path: cortex-config.yml
            name: cortex-config
          name: cortex-config
        - persistentVolumeClaim:
            claimName: cortex-claim
          name: cortex-claim
        - persistentVolumeClaim:
            claimName: cortex-prometheus-claim
          name: cortex-prometheus-claim