apiVersion: v1
kind: ConfigMap
metadata:
    name: prometheus-config
    namespace: m3db-test
data:
    prometheus-config.yml: |-
        global:
            external_labels:
              monitor: test
            scrape_interval:     15s
            evaluation_interval: 15s

        remote_write:
          - url: m3coordinator-simple-cluster.m3db-test.svc.cluster.local:7201/api/v1/prom/remote/write

        scrape_configs:
          - job_name: prometheus
            static_configs:
              - targets: ['localhost:9090']