apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: m3db-node
  namespace: m3db-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: m3db-node
subjects:
- kind: ServiceAccount
  name: default
  namespace: m3db-test