apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: m3db-node
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - add-sys-resource-cap
  resources:
  - securitycontextconstraints
  verbs:
  - use